package compilador.lexico;

public enum TipoToken {
	PALAVRA_CHAVE, IDENTIFICADOR, NUMERO_INTEIRO, 
	NUMERO_REAL, DELIMITADOR, COMANDO_ATRIBUICAO, 
	OPERADOR_RELACIONAL, OPERADOR_ADITIVO, OPERADOR_MULTIPLICATIVO, OPERADOR_LOGICO;
}
